---
- name: git server setup and administation
  hosts: git
  become: true 
  vars:
    gits_location: /srv/gits
    backups_location: /srv/backups
    git_user: git
    git_group: git


  tasks:
  - name: Install a required packages
    tags:
      - setup
    ansible.builtin.apt:
      pkg:
        - git
        - fail2ban
      state: present
    notify:
      - start fail2ban
  - name: Create user
    tags: 
      - setup
    user:
      name: git
      shell: /usr/bin/git-shell
      home: /home/git
  - name: Upload ssh key
    tags:
      - ssh
      - setup
    ansible.builtin.copy:
      src: ./home_git_ssh/authorized_keys
      dest: /home/git/.ssh/authorized_keys
      owner: git
      group: git
      mode: 0644
  - name: Create directories for git server
    tags: 
      - setup 
    file:
      path: "{{ item }}"
      state: directory
      owner: "{{ git_user}}"
      group: "{{ git_group }}"
      mode: 0775
    loop:
      - "{{ gits_location }}"
      - "{{ backups_location }}"
  - name: Setup backup o gits
    tags:
      - setup
      - setup_backup
    command: echo Enable backup
    notify:
      - clone backup repo 
      - install timer and service
      - enable timer and service
  - name: Init git repo
    tags: init_git
    command: echo "task will fail without action"
    notify:
      - create git repo dir
      - init bare git repo
      - fix git repo ownership
#### Handlers
  handlers:
    - name: create git repo dir
      file:
        path: "{{ gits_location }}/{{ repo_name }}"
        state: directory
        owner: git
        group: git
        mode: 0775
    - name: init bare git repo
      command: git init --bare "{{ gits_location }}/{{ repo_name }}"
    - name: fix git repo ownership
      file:
       dest: "{{ gits_location }}/{{ repo_name }}"
       owner: "{{ git_user}}"
       group: "{{ git_group }}"
       #mode: 0775
       recurse: true
    - name: start fail2ban
      ansible.builtin.service:
        name: fail2ban
        state: started
        enabled: yes
    - name: clone backup repo
      ansible.builtin.git:
        repo: https://github.com/adrianbiro/rotate_tar_backup.git
        dest: "{{ gits_location }}/rotate_tar_backup"
    - name: install timer and service
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "/etc/systemd/system/"
        owner: root
        group: root
        remote_src: yes
      with_fileglob:
        - "{{ gits_location }}/rotate_tar_backup/gitsBackup.*"
    - name: enable timer and service
      ansible.builtin.service:
        name: "{{ item }}"
        state: started
        enabled: yes
      with_items:
        - gitsBackup.service
        - gitsBackup.timer


